# Generated by Django 3.2 on 2022-03-03 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import file_protector.apps.uploader.utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=128)),
                ('uploaded_file', models.FileField(blank=True, upload_to=file_protector.apps.uploader.utils.file_path)),
                ('uploaded_url', models.URLField(blank=True)),
                ('generated_url', models.URLField(blank=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('visited', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('agent', models.TextField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='uploader.uploader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]