# Generated by Django 3.2 on 2022-03-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploader',
            name='correct_pass_counter',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]